function cdc1() {
  var d = document.getElementById("gallery")
  d.innerHTML =
  '<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Manualidades<div class="image_box popup" style="background-image: url(Talleres/manualidades1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Martes y Jueves</li><li>Horarios:</li><li>Martes: 1:30pm - 5:30pm</li><li>Jueves: 10:00am - 6:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Yoga<div class="image_box popup" style="background-image: url(Talleres/yoga1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Lunes y Miércoles</li><li>Horarios:</li><li>4:00pm - 5:30pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Belleza<div class="image_box popup" style="background-image: url(Talleres/belleza1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>1:00pm - 2:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Estilismo 1<div class="image_box popup" style="background-image: url(Talleres/estilismo1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>12:00pm - 3:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Estilismo 2<div class="image_box popup" style="background-image: url(Talleres/estilismo2.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>9:00am - 12:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Uñas<div class="image_box popup" style="background-image: url(Talleres/unias1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Viernes</li><li>Horarios:</li><li>9:00am - 12:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Corte y Confección<div class="image_box popup" style="background-image: url(Talleres/confeccion1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes, Miercoles, Viernes y Sábado</li><li>Horarios:</li><li>Lunes, Miércoles y Sábado: 9:30am - 1:30pm</li><li>Lunes, Miércoles y Viernes: 3:00pm - 7:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Bisutería<div class="image_box popup" style="background-image: url(Talleres/bisuteria1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Martes, Jueves y Sábado</li><li>Horarios:</li><li>10:00am - 1:30pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Alta Costura<div class="image_box popup" style="background-image: url(Talleres/costura1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Martes, Jueves y Sábado</li><li>Horarios:</li><li>Martes y Jueves: 3:00pm - 7:00pm</li><li>Sábado: 9:30am - 1:30pm</li></ul></font></center></div></div></div></div>';
}
function cdc2() {
  var d = document.getElementById("gallery")
  d.innerHTML =
  '<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Estilismo<div class="image_box popup" style="background-image: url(Talleres/estilismo1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>9:00am - 12:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Jazz<div class="image_box popup" style="background-image: url(Talleres/jazz1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $120</li><li>Días: Martes y Jueves</li><li>Horarios:</li>4:30pm - 6:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Masajes<div class="image_box popup" style="background-image: url(Talleres/masajes1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $120</li><li>Días: Lunes</li><li>Horarios:</li><li>4:00pm - 7:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Música<div class="image_box popup" style="background-image: url(Talleres/musica1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $120</li><li>Días: Lunes y Miércoles</li><li>Horarios:</li><li>3:30pm - 5:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Ballet<div class="image_box popup" style="background-image: url(Talleres/ballet1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $120</li><li>Días: Lunes, Martes, Miércoles y Viernes</li><li>Horarios:</li><li>3:00pm - 4:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">TaeKwonDo<div class="image_box popup" style="background-image: url(Talleres/taekwondo1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $120</li><li>Días: Martes y Viernes</li><li>Horarios:</li><li>5:00pm - 6:00pm</li></ul></font></center></div></div></div></div>';
}
function cdc3() {
  var d = document.getElementById("gallery")
  d.innerHTML =
  '<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Asistente Ejecutivo<div class="image_box popup" style="background-image: url(Talleres/asistente1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>8:00am - 1:00pm</li><li>2:00pm - 7:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Masajes<div class="image_box popup" style="background-image: url(Talleres/masajes1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Lunes</li><li>Horarios:</li><li>9:00am - 11:00am</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Manualidades<div class="image_box popup" style="background-image: url(Talleres/manualidades1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Lunes, Martes y Miércoles</li><li>Horarios:</li><li>12:00pm - 3:00pm</li><li>3:00pm - 6:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Estilismo 1<div class="image_box popup" style="background-image: url(Talleres/estilismo1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>8:00am - 11:00am</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Estilismo 2<div class="image_box popup" style="background-image: url(Talleres/estilismo2.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>11:00am - 2:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Uñas<div class="image_box popup" style="background-image: url(Talleres/unias1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Miércoles</li><li>Horarios:</li><li>8:00am - 11:00am</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Inglés<div class="image_box popup" style="background-image: url(Talleres/ingles1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Martes y Jueves</li><li>Horarios:</li><li>8:00am - 2:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Computación<div class="image_box popup" style="background-image: url(Talleres/computacion1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $150</li><li>Mensualidades: $150</li><li>Días: Lunes, Miércoles y Viernes</li><li>Horarios:</li><li>9:30am - 11:30am</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Artes Marciales<div class="image_box popup" style="background-image: url(Talleres/artesmarciales1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Lunes, Miércoles y Viernes</li><li>Horarios:</li><li>3:30pm - 6:30pm</li></ul></font></center></div></div></div></div>';
}
function cdc4() {
  var d = document.getElementById("gallery")
  d.innerHTML =
  '<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Gastronomía<div class="image_box popup" style="background-image: url(Talleres/gastronomia1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes, Miércoles y Viernes</li><li>Horarios:</li><li>9:00am - 12:00pm</li><li>3:00pm - 7:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Inglés<div class="image_box popup" style="background-image: url(Talleres/ingles1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes, Miércoles y Viernes</li><li>Horarios:</li><li>12:00pm - 2:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Computación<div class="image_box popup" style="background-image: url(Talleres/computacion1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $150</li><li>Mensualidades: $150</li><li>Días: Lunes, Miércoles y Viernes</li><li>Horarios:</li><li>8:00am - 10:00am</li><li>10:00am - 12:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Estilismo 1<div class="image_box popup" style="background-image: url(Talleres/estilismo1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>9:00am - 12:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Estilismo 2<div class="image_box popup" style="background-image: url(Talleres/estilismo2.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>10:00am - 1:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Uñas<div class="image_box popup" style="background-image: url(Talleres/unias1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Miércoles</li><li>Horarios:</li><li>12:30pm - 3:30pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Corte de Cabello<div class="image_box popup" style="background-image: url(Talleres/cortecabello1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Martes y Jueves</li><li>Horarios:</li><li>12:00pm - 3:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Trenzas<div class="image_box popup" style="background-image: url(Talleres/trenzas1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Lunes y Jueves</li><li>Horarios:</li><li>12:00pm - 3:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Peinado Infantil<div class="image_box popup" style="background-image: url(Talleres/peinadoinfantil1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Lunes</li><li>Horarios:</li><li>12:30pm - 3:30pm</li></ul></font></center></div></div></div></div>';
}
function cdc5() {
  var d = document.getElementById("gallery")
  d.innerHTML =
  '<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Alta Costura<div class="image_box popup" style="background-image: url(Talleres/costura1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes, Miércoles y Viernes</li><li>Horarios:</li><li>4:00pm - 7:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Corte y Confección<div class="image_box popup" style="background-image: url(Talleres/confeccion1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes, Miércoles y Viernes</li><li>Horarios:</li><li>4:00pm - 7:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Bordado<div class="image_box popup" style="background-image: url(Talleres/bordado1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Lunes,  Miércoles y Viernes</li><li>Horarios:</li><li>4:00pm - 7:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Confección de Prendas<div class="image_box popup" style="background-image: url(Talleres/confecciondeprendas1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Lunes, Miércoles y Viernes</li><li>Horarios:</li><li>4:00pm - 7:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Estilismo<div class="image_box popup" style="background-image: url(Talleres/estilismo1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>4:00pm - 7:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Ritmos Latinos<div class="image_box popup" style="background-image: url(Talleres/ritmoslatinos1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>5:00pm - 6:00pm</li></ul></font></center></div></div></div></div>';
}
function cdc6() {
  var d = document.getElementById("gallery")
  d.innerHTML =
  '<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Gastronomía<div class="image_box popup" style="background-image: url(Talleres/gastronomia1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>9:00am - 1:00pm y 4:00pm - 7:00pm </li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Estilismo 1<div class="image_box popup" style="background-image: url(Talleres/estilismo1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>4:00pm - 7:00pm y 9:00am - 12:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Estilismo 2<div class="image_box popup" style="background-image: url(Talleres/estilismo2.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>12:00pm - 3:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Uñas<div class="image_box popup" style="background-image: url(Talleres/unias1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Martes y Jueves</li><li>Horarios:</li><li>4:00pm - 6:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Corte y Confección<div class="image_box popup" style="background-image: url(Talleres/confeccion1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Martes, Jueves y Viernes</li><li>Horarios:</li><li>2:00pm - 7:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Alta Costura<div class="image_box popup" style="background-image: url(Talleres/costura1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes, Miércoles, Jueves y Viernes</li><li>Horarios:</li><li>2:30pm - 7:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Inglés<div class="image_box popup" style="background-image: url(Talleres/ingles1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes, Miércoles y Viernes</li><li>Horarios:</li><li>4:00pm - 6:30pm</li></ul></font></center></div></div></div></div>';
}
function cdc7() {
  var d = document.getElementById("gallery")
  d.innerHTML =
  '<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Diplomado de Pintura y Bordado<div class="image_box popup" style="background-image: url(Talleres/pinturaybordado1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Miércoles, Jueves y Viernes</li><li>Horarios:</li><li>4:00pm - 7:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Estilismo 1<div class="image_box popup" style="background-image: url(Talleres/estilismo1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>9:00am - 12:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Estilismo 2<div class="image_box popup" style="background-image: url(Talleres/estilismo2.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>8:30am - 11:30am y 12:30pm - 2:30pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Pasta Flexible<div class="image_box popup" style="background-image: url(Talleres/pastaflexible1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $150</li><li>Días: Miércoles, Jueves y Viernes</li><li>Horarios:</li><li>4:00pm - 7:00pm</li></ul></font></center></div></div></div></div>';
}
function cdc8() {
  var d = document.getElementById("gallery")
  d.innerHTML =
  '<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Estilismo 1<div class="image_box popup" style="background-image: url(Talleres/estilismo1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes, Miércoles y Viernes</li><li>Horarios:</li><li>8:30am - 12:30pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Peinado Infantil<div class="image_box popup" style="background-image: url(Talleres/peinadoinfantil1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Martes y Jueves</li><li>Horarios:</li><li>2:00pm - 6:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Cocina Navideña<div class="image_box popup" style="background-image: url(Talleres/comidanavidenia.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción:$100</li><li>Mensualidades: $100</li><li>Días: Miércoles</li><li>Horarios:</li><li>2:00pm - 6:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Alta Costura<div class="image_box popup" style="background-image: url(Talleres/costura1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Martes y Jueves</li><li>Horarios:</li><li>11:30am - 2:30pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Corte y Confección<div class="image_box popup" style="background-image: url(Talleres/confeccion1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes y Miércoles</li><li>Horarios:</li><li>Lunes: 9:00am - 2:00pm y Miércoles: 11:30am - 2:30pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Diseño de Modas<div class="image_box popup" style="background-image: url(Talleres/diseniodemodas1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 6 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Martes y Jueves</li><li>Horarios:</li><li>8:30am - 11:30am</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Blancos<div class="image_box popup" style="background-image: url(Talleres/blancos.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Miércoles</li><li>Horarios:</li><li>8:30am- 11:30am</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Inglés Intermedio<div class="image_box popup" style="background-image: url(Talleres/inglesintermedio1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Miércoles y Jueves</li><li>Horarios:</li><li>Miércoles: 7:00am - 9:00am y Jueves: 7:00am - 11:00am</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Inglés Básico<div class="image_box popup" style="background-image: url(Talleres/inglesbasico1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 6 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Lunes, Martes y Miércoles</li><li>Horarios:</li><li>7:00am - 9:00am</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Hatha Yoga<div class="image_box popup" style="background-image: url(Talleres/hathayoga1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes a Viernes</li><li>Horarios:</li><li>8:00am - 9:00am y 9:00am - 10:00am</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Manualidades<div class="image_box popup" style="background-image: url(Talleres/manualidades1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: $100</li><li>Mensualidades: $100</li><li>Días: Lunes, Miércoles y Viernes</li><li>Horarios:</li><li>3:00pm - 7:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Taller de Piñatas<div class="image_box popup" style="background-image: url(Talleres/tallerdepiñatas1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 3 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Martes y Jueves</li><li>Horarios:</li><li>3:00pm - 5:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Baile de Salón<div class="image_box popup" style="background-image: url(Talleres/bailedesalon1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 1 año</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $100</li><li>Días: Martes y Jueves</li><li>Horarios:</li><li>10:00am - 1:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Maquillaje Profesional<div class="image_box popup" style="background-image: url(Talleres/maquillajeprofesional1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 6 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $150</li><li>Días: Jueves</li><li>Horarios:</li><li>2:00pm - 4:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Uñas<div class="image_box popup" style="background-image: url(Talleres/unias1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 6 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $150</li><li>Días: Martes</li><li>Horarios:</li><li>2:00pm - 6:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Inglés 1<div class="image_box popup" style="background-image: url(Talleres/ingles1.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 6 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $150</li><li>Días: Martes</li><li>Horarios:</li><li>2:00pm - 6:00pm</li></ul></font></center></div></div></div></div>'
  +'<div class="wpb_column vc_column_container vc_col-xs-6 vc_col-sm-2"><div class="vc_column-inner"><div class="wpb_wrapper"><div class="thumbnail">Inglés 2<div class="image_box popup" style="background-image: url(Talleres/ingles2.png); height: 155px;" data-k="0" data-component="gallery"></div><center><FONT SIZE=1><ul><li>Duración: 6 meses</li><li>Costo de Inscripción: Gratuito</li><li>Mensualidades: $150</li><li>Días: Lunes, Martes y Miércoles</li><li>Horarios:</li><li>7:00am - 9:00am</li></ul></font></center></div></div></div></div>';
}
